namespace CDK.DataAccess.Repositories.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class SeoForUnits : DbMigration
    {
        public override void Up()
        {
            AddColumn("ddf.Unit", "LastExternalUpdate", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AddColumn("ddf.Unit", "Created", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AddColumn("ddf.Unit", "CreatedBy", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.Unit", "LastUpdateBy", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.Unit", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.Unit", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("ddf.Unit", "SeoURI", c => c.String(unicode: false));
            AddColumn("ddf.Building", "LastExternalUpdate", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AddColumn("ddf.Building", "Created", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AddColumn("ddf.Building", "CreatedBy", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.Building", "LastUpdateBy", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.Building", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.Building", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("ddf.Building", "SeoURI", c => c.String(unicode: false));
            AddColumn("ddf.UnitPhoto", "ThumbnailUri", c => c.String(unicode: false));
            AddColumn("ddf.UnitPhoto", "LargeUri", c => c.String(unicode: false));
            AddColumn("ddf.UnitPhoto", "SmallUri", c => c.String(unicode: false));
            AddColumn("ddf.UnitPhoto", "AltText", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.UnitPhoto", "PhotoName", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.UnitPhoto", "PhotoDescription", c => c.String(unicode: false));
            AddColumn("ddf.UnitPhoto", "Created", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AddColumn("ddf.UnitPhoto", "CreatedBy", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.UnitPhoto", "LastUpdateBy", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.UnitPhoto", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.UnitPhoto", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("ddf.UnitPhoto", "SeoURI", c => c.String(unicode: false));
            AddColumn("ddf.UnitPhoto", "LastExternalUpdate", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AddColumn("cdk.Developer", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.Developer", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("cdk.Developer", "SeoURI", c => c.String(unicode: false));
            AddColumn("cdk.Development", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.Development", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("cdk.Development", "SeoURI", c => c.String(unicode: false));
            AddColumn("cdk.NeighborhoodArea", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.NeighborhoodArea", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("cdk.NeighborhoodArea", "SeoURI", c => c.String(unicode: false));
            AddColumn("cdk.MetroArea", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.MetroArea", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("cdk.MetroArea", "SeoURI", c => c.String(unicode: false));
            AddColumn("cdk.NeighborhoodGuide", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.NeighborhoodGuide", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("cdk.NeighborhoodGuide", "SeoURI", c => c.String(unicode: false));
            AddColumn("cdk.NeighborhoodGuidePhoto", "AltText", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.NeighborhoodGuidePhoto", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.NeighborhoodGuidePhoto", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("cdk.NeighborhoodGuidePhoto", "SeoURI", c => c.String(unicode: false));
            AddColumn("cdk.NeighborhoodGuideVideo", "AltText", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.NeighborhoodGuideVideo", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.NeighborhoodGuideVideo", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("cdk.NeighborhoodGuideVideo", "SeoURI", c => c.String(unicode: false));
            AddColumn("cdk.DevelopmentFloorPlan", "AltText", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.DevelopmentFloorPlan", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.DevelopmentFloorPlan", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("cdk.DevelopmentFloorPlan", "SeoURI", c => c.String(unicode: false));
            AddColumn("cdk.DevelopmentPhoto", "AltText", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.DevelopmentPhoto", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.DevelopmentPhoto", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("cdk.DevelopmentPhoto", "SeoURI", c => c.String(unicode: false));
            AddColumn("cdk.DevelopmentVideo", "AltText", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.DevelopmentVideo", "SeoTitle", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.DevelopmentVideo", "SeoMetaDescription", c => c.String(unicode: false));
            AddColumn("cdk.DevelopmentVideo", "SeoURI", c => c.String(unicode: false));
            AlterColumn("ddf.Unit", "LastUpdate", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("ddf.Unit", "SeoDescription", c => c.String(unicode: false));
            AlterColumn("ddf.Unit", "SeoSlug", c => c.String(unicode: false));
            AlterColumn("ddf.Building", "LastUpdate", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("ddf.Building", "SeoDescription", c => c.String(unicode: false));
            AlterColumn("ddf.Building", "SeoSlug", c => c.String(unicode: false));
            AlterColumn("ddf.UnitPhoto", "LastUpdate", c => c.DateTime(nullable: false, precision: 7, storeType: "datetime2"));
            AlterColumn("ddf.UnitPhoto", "SeoDescription", c => c.String(unicode: false));
            AlterColumn("ddf.UnitPhoto", "SeoSlug", c => c.String(unicode: false));
            DropColumn("ddf.Unit", "LastDdfUpdate");
            DropColumn("ddf.Building", "LastDdfUpdate");
            DropColumn("ddf.UnitPhoto", "FolderPath");
            DropColumn("ddf.UnitPhoto", "PhotoThumbnailUri");
            DropColumn("ddf.UnitPhoto", "PhotoSmallUri");
            DropColumn("ddf.UnitPhoto", "PhotoLargeUri");
            DropColumn("ddf.UnitPhoto", "LastDdfUpdate");
            DropColumn("ddf.UnitPhoto", "SeoAltText");
            DropColumn("cdk.NeighborhoodGuidePhoto", "PhotoAlt");
            DropColumn("cdk.DevelopmentFloorPlan", "PhotoAlt");
            DropColumn("cdk.DevelopmentPhoto", "PhotoAlt");
        }
        
        public override void Down()
        {
            AddColumn("cdk.DevelopmentPhoto", "PhotoAlt", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.DevelopmentFloorPlan", "PhotoAlt", c => c.String(maxLength: 255, unicode: false));
            AddColumn("cdk.NeighborhoodGuidePhoto", "PhotoAlt", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.UnitPhoto", "SeoAltText", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.UnitPhoto", "LastDdfUpdate", c => c.DateTime(nullable: false));
            AddColumn("ddf.UnitPhoto", "PhotoLargeUri", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.UnitPhoto", "PhotoSmallUri", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.UnitPhoto", "PhotoThumbnailUri", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.UnitPhoto", "FolderPath", c => c.String(maxLength: 255, unicode: false));
            AddColumn("ddf.Building", "LastDdfUpdate", c => c.DateTime(nullable: false));
            AddColumn("ddf.Unit", "LastDdfUpdate", c => c.DateTime(nullable: false));
            AlterColumn("ddf.UnitPhoto", "SeoSlug", c => c.String(maxLength: 8000, unicode: false));
            AlterColumn("ddf.UnitPhoto", "SeoDescription", c => c.String(maxLength: 8000, unicode: false));
            AlterColumn("ddf.UnitPhoto", "LastUpdate", c => c.DateTime(nullable: false));
            AlterColumn("ddf.Building", "SeoSlug", c => c.String(maxLength: 8000, unicode: false));
            AlterColumn("ddf.Building", "SeoDescription", c => c.String(maxLength: 8000, unicode: false));
            AlterColumn("ddf.Building", "LastUpdate", c => c.DateTime(nullable: false));
            AlterColumn("ddf.Unit", "SeoSlug", c => c.String(maxLength: 8000, unicode: false));
            AlterColumn("ddf.Unit", "SeoDescription", c => c.String(maxLength: 8000, unicode: false));
            AlterColumn("ddf.Unit", "LastUpdate", c => c.DateTime(nullable: false));
            DropColumn("cdk.DevelopmentVideo", "SeoURI");
            DropColumn("cdk.DevelopmentVideo", "SeoMetaDescription");
            DropColumn("cdk.DevelopmentVideo", "SeoTitle");
            DropColumn("cdk.DevelopmentVideo", "AltText");
            DropColumn("cdk.DevelopmentPhoto", "SeoURI");
            DropColumn("cdk.DevelopmentPhoto", "SeoMetaDescription");
            DropColumn("cdk.DevelopmentPhoto", "SeoTitle");
            DropColumn("cdk.DevelopmentPhoto", "AltText");
            DropColumn("cdk.DevelopmentFloorPlan", "SeoURI");
            DropColumn("cdk.DevelopmentFloorPlan", "SeoMetaDescription");
            DropColumn("cdk.DevelopmentFloorPlan", "SeoTitle");
            DropColumn("cdk.DevelopmentFloorPlan", "AltText");
            DropColumn("cdk.NeighborhoodGuideVideo", "SeoURI");
            DropColumn("cdk.NeighborhoodGuideVideo", "SeoMetaDescription");
            DropColumn("cdk.NeighborhoodGuideVideo", "SeoTitle");
            DropColumn("cdk.NeighborhoodGuideVideo", "AltText");
            DropColumn("cdk.NeighborhoodGuidePhoto", "SeoURI");
            DropColumn("cdk.NeighborhoodGuidePhoto", "SeoMetaDescription");
            DropColumn("cdk.NeighborhoodGuidePhoto", "SeoTitle");
            DropColumn("cdk.NeighborhoodGuidePhoto", "AltText");
            DropColumn("cdk.NeighborhoodGuide", "SeoURI");
            DropColumn("cdk.NeighborhoodGuide", "SeoMetaDescription");
            DropColumn("cdk.NeighborhoodGuide", "SeoTitle");
            DropColumn("cdk.MetroArea", "SeoURI");
            DropColumn("cdk.MetroArea", "SeoMetaDescription");
            DropColumn("cdk.MetroArea", "SeoTitle");
            DropColumn("cdk.NeighborhoodArea", "SeoURI");
            DropColumn("cdk.NeighborhoodArea", "SeoMetaDescription");
            DropColumn("cdk.NeighborhoodArea", "SeoTitle");
            DropColumn("cdk.Development", "SeoURI");
            DropColumn("cdk.Development", "SeoMetaDescription");
            DropColumn("cdk.Development", "SeoTitle");
            DropColumn("cdk.Developer", "SeoURI");
            DropColumn("cdk.Developer", "SeoMetaDescription");
            DropColumn("cdk.Developer", "SeoTitle");
            DropColumn("ddf.UnitPhoto", "LastExternalUpdate");
            DropColumn("ddf.UnitPhoto", "SeoURI");
            DropColumn("ddf.UnitPhoto", "SeoMetaDescription");
            DropColumn("ddf.UnitPhoto", "SeoTitle");
            DropColumn("ddf.UnitPhoto", "LastUpdateBy");
            DropColumn("ddf.UnitPhoto", "CreatedBy");
            DropColumn("ddf.UnitPhoto", "Created");
            DropColumn("ddf.UnitPhoto", "PhotoDescription");
            DropColumn("ddf.UnitPhoto", "PhotoName");
            DropColumn("ddf.UnitPhoto", "AltText");
            DropColumn("ddf.UnitPhoto", "SmallUri");
            DropColumn("ddf.UnitPhoto", "LargeUri");
            DropColumn("ddf.UnitPhoto", "ThumbnailUri");
            DropColumn("ddf.Building", "SeoURI");
            DropColumn("ddf.Building", "SeoMetaDescription");
            DropColumn("ddf.Building", "SeoTitle");
            DropColumn("ddf.Building", "LastUpdateBy");
            DropColumn("ddf.Building", "CreatedBy");
            DropColumn("ddf.Building", "Created");
            DropColumn("ddf.Building", "LastExternalUpdate");
            DropColumn("ddf.Unit", "SeoURI");
            DropColumn("ddf.Unit", "SeoMetaDescription");
            DropColumn("ddf.Unit", "SeoTitle");
            DropColumn("ddf.Unit", "LastUpdateBy");
            DropColumn("ddf.Unit", "CreatedBy");
            DropColumn("ddf.Unit", "Created");
            DropColumn("ddf.Unit", "LastExternalUpdate");
        }
    }
}
